from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field


Modality = Literal["pdf", "word", "excel", "html", "image", "audio", "unknown"]


class SourceTrace(BaseModel):
    file: str  # Source file: original file path corresponding to the artifact.
    page: Optional[int] = None  # Source page: page number in paginated files such as PDFs.
    bbox: Optional[List[float]] = None  # Source bounding box: region bounds for layout or OCR output.
    operator: str  # Source operator: operator_name that generated this artifact.


class Artifact(BaseModel):
    id: str  # Artifact id: stable artifact identifier unique within a sample.
    type: str  # Artifact type: business type used downstream to recognize the content shape.
    text: Optional[str] = None  # Text content: human-readable text carried by the artifact.
    data: Dict[str, Any] = Field(default_factory=dict)  # Extra data: structured supplemental fields for the artifact.
    source_trace: SourceTrace  # Source trace: records which file, position, and operator produced the artifact.


class DataItem(BaseModel):
    id: str  # Sample id: stable sample identifier derived from the file name or external input.
    modality: Modality = "unknown"  # Content modality: determines which parsing operators the sample enters.
    source: Dict[str, Any]  # Source info: raw metadata such as input file path and format.
    payload: Dict[str, Any] = Field(default_factory=dict)  # Processing payload: input parameters passed to operators.
    meta: Dict[str, Any] = Field(default_factory=dict)  # General metadata: non-business fields such as creation time.
    intermediate: Dict[str, Any] = Field(default_factory=dict)  # Intermediate cache: temporary results shared between steps.
    metrics: Dict[str, Any] = Field(default_factory=dict)  # Sample metrics: accumulated statistics from the parsing process.
    issues: List[Dict[str, Any]] = Field(default_factory=list)  # Issue list: diagnostic records produced during sample processing.
    artifacts: List[Artifact] = Field(default_factory=list)  # Parsing artifacts: structured results generated by operators.
    action: str = "pending"  # Processing state: current action state of the sample in the workflow.

    @classmethod
    def from_path(cls, path: Path) -> "DataItem":
        """Create a data item to parse from a file path.

        Business logic:
            1. Read the file suffix and map it to the pdf, word, excel, image, audio, or unknown modality.
            2. Use the file stem as the sample id and record the source path and format.
            3. Write the UTC creation time and return a DataItem ready for the workflow.

        Args:
            path: Input file path.

        Returns:
            DataItem: Parsing sample containing source, modality, payload, and creation time.

        Examples:
            >>> DataItem.from_path(Path("demo.pdf")).modality
            'pdf'"""
        suffix = path.suffix.lower()
        modality: Modality = "unknown"
        if suffix == ".pdf":  # PDF suffix: route into document text and layout parsing.
            modality = "pdf"
        elif suffix in {".docx"}:
            modality = "word"
        elif suffix in {".xlsx", ".xls"}:
            modality = "excel"
        elif suffix in {".html", ".htm"}:
            modality = "html"
        elif suffix in {".png", ".jpg", ".jpeg", ".bmp", ".webp"}:
            modality = "image"
        elif suffix in {".wav", ".mp3", ".m4a", ".flac", ".aac"}:
            modality = "audio"

        return cls(
            id=path.stem,
            modality=modality,
            source={"path": str(path), "format": suffix.lstrip(".")},
            payload={"path": str(path)},
            meta={"created_at": datetime.now(timezone.utc).isoformat()},
        )
