from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Iterable

from parse_engine.models import DataItem


def write_report(run_dir: Path, metrics: Dict[str, Any], items: Iterable[DataItem]) -> Path:
    """Generate a Markdown summary report for the workflow.

    Business logic:
        1. Materialize the sample iterator into a list to prepare failed-sample details.
        2. Write totals and modality, action, artifact, and issue distributions based on metrics.
        3. Append the failed-file list and save the result as report.md.

    Args:
        run_dir: Workflow run directory for this execution.
        metrics: Summary metrics generated by collect_metrics.
        items: Iterable of data items after workflow processing has finished.

    Returns:
        Path: Path to the generated report.md file.

    Examples:
        >>> Path("report.md").suffix
        '.md'"""
    item_list = list(items)
    report_path = run_dir / "report.md"
    lines = [
        "# Content Parsing Report",
        "",
        f"- Total samples: {metrics.get('input_total_count', metrics.get('total', 0))}",
        f"- Current run samples: {metrics.get('total', 0)}",
        f"- Modality distribution: `{json.dumps(metrics.get('by_modality', {}), ensure_ascii=False)}`",
        f"- Actions: `{json.dumps(metrics.get('by_action', {}), ensure_ascii=False)}`",
        f"- Artifact types: `{json.dumps(metrics.get('artifacts', {}), ensure_ascii=False)}`",
        f"- Issue types: `{json.dumps(metrics.get('issues', {}), ensure_ascii=False)}`",
        f"- resume_enabled: {metrics.get('resume_enabled', False)}",
        f"- skipped_count: {metrics.get('skipped_count', 0)}",
        f"- processed_count: {metrics.get('processed_count', metrics.get('total', 0))}",
        f"- Completed count: {metrics.get('completed_count', 0)}",
        f"- Historical completed count: {metrics.get('historical_completed_count', metrics.get('skipped_count', 0))}",
        f"- Newly processed count: {metrics.get('newly_processed_count', metrics.get('processed_count', metrics.get('total', 0)))}",
        f"- Current completed count: {metrics.get('current_completed_count', metrics.get('completed_count', 0))}",
        f"- Pending count: {metrics.get('pending_count', max(0, metrics.get('input_total_count', metrics.get('total', 0)) - metrics.get('completed_count', 0)))}",
        f"- concurrency: {metrics.get('concurrency', 1)}",
        f"- concurrency_enabled: {metrics.get('concurrency_enabled', False)}",
        f"- parallelized_count: {metrics.get('parallelized_count', 0)}",
        "",
        "## Failed Files",
        "",
    ]
    failed = [item for item in item_list if item.action == "failed"]
    if not failed:  # No failed samples: make the success state explicit in the report.
        lines.append("None.")
    else:
        for item in failed:  # Failure details: list paths and issues for manual investigation.
            lines.append(f"- `{item.source.get('path')}`: {item.issues}")

    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path
