from __future__ import annotations

from pathlib import Path
from typing import Any


def write_report(path: Path, stats: dict[str, Any], groups: list[dict[str, Any]]) -> None:
    """Write the Markdown report for a single deduplication run.

    Business logic:
        1. Build the summary and issue-distribution tables from metrics.
        2. Render a preview table from the first 20 duplicate groups.
        3. Write the Markdown report, including output file descriptions.

    Args:
        path (Path): Output path for the report.
        stats (dict[str, Any]): Run-level metrics generated by the executor.
        groups (list[dict[str, Any]]): List of duplicate groups.

    Returns:
        None: The report is written to disk and nothing is returned.

    Examples:
        >>> write_report(Path("report.md"), {"total_count": 0}, [])  # doctest: +SKIP
    """
    issue_lines = "\n".join(
        f"| {issue} | {count} |"
        for issue, count in sorted(stats.get("issue_distribution", {}).items(), key=lambda pair: (-pair[1], pair[0]))  # Keep issue ordering stable by count desc, then name asc.
    )
    if not issue_lines:  # Keep the Markdown table valid when no item issues were recorded.
        issue_lines = "| none | 0 |"

    group_lines = "\n".join(
        f"| {group['group_id']} | {group['modality']} | {len(group['member_ids'])} | {group.get('keep_id', '')} | "
        f"{', '.join(group.get('reasons', []))} |"
        for group in groups[:20]  # Preview only the first 20 duplicate groups; the full data remains in the JSONL output.
    )
    if not group_lines:  # Show an explicit empty duplicate table instead of leaving a blank section.
        group_lines = "| none | - | 0 | - | - |"

    total = max(int(stats.get("total_count", 0)), 1)
    remove_rate = stats.get("removed_count", 0) / total

    content = f"""# Deduplication Report

## Summary

| Metric | Value |
| --- | ---: |
| workflow_id | {stats.get("workflow_id")} |
| modality | {stats.get("modality")} |
| total_count | {stats.get("total_count", 0)} |
| kept_count | {stats.get("kept_count", 0)} |
| removed_count | {stats.get("removed_count", 0)} |
| review_count | {stats.get("review_count", 0)} |
| duplicate_group_count | {stats.get("duplicate_group_count", 0)} |
| duplicate_edge_count | {stats.get("duplicate_edge_count", 0)} |
| resume_enabled | {stats.get("resume_enabled", False)} |
| skipped_count | {stats.get("skipped_count", 0)} |
| processed_count | {stats.get("processed_count", stats.get("total_count", 0))} |
| completed_count | {stats.get("completed_count", 0)} |
| remove_rate | {remove_rate:.2%} |
| elapsed_seconds | {stats.get("elapsed_seconds", 0)} |
| throughput_qps | {stats.get("throughput_qps", 0)} |

## Issue Distribution

| Issue | Count |
| --- | ---: |
{issue_lines}

## Duplicate Groups Preview

| Group | Modality | Members | Keep | Reasons |
| --- | --- | ---: | --- | --- |
{group_lines}

## Output Files

- kept.jsonl: retained samples.
- removed.jsonl: samples removed because another representative was selected.
- duplicate_groups.jsonl: duplicate clusters, reasons, scores, keep/remove decision.
- metrics.json: run-level metrics.
- operator_logs.jsonl: operator-level audit log.
- checkpoints/: step snapshots for interrupted runs.
"""
    path.write_text(content, encoding="utf-8")
