from typing import Any

from denoise_workflow_engine.utilities.video.base import *  # noqa: F403


class VideoAIGCDetector:
    def detect(self, item: dict[str, Any], operator: "VideoAIGCDetectOperator") -> tuple[float | None, dict[str, Any]]:
        """Run one video AIGC detector backend and return a score plus evidence.

        Business logic:
            1. Accept the current sample and operator runtime context.
            2. Return a score in the range [0, 1] when the detector can decide.
            3. Return structured evidence for debugging, reporting, and fallback handling.

        Args:
                item (dict[str, Any]): Current sample dictionary.
                operator (VideoAIGCDetectOperator): Owning operator instance.

        Returns:
            tuple[float | None, dict[str, Any]]: Detector score and evidence payload.

        Examples:
            >>> isinstance(VideoAIGCDetector(), VideoAIGCDetector)
            True
        """
        raise NotImplementedError


class LocalHeuristicVideoAIGCDetector(VideoAIGCDetector):
    AI_KEYWORDS: tuple[str, ...] = (
        "ai generated",
        "ai-generated",
        "aigc",
        "generated video",
        "synthetic",
        "model-generated",
        "synthetic video",
        "generated by ai",
        "生成视频",
        "ai视频",
        "数字人",
        "虚拟人",
        "kling",
        "veo",
        "seedance",
        "ltx",
        "mova",
        "ovi",
        "sora",
        "runway",
        "wanx",
        "hunyuan",
    )  # Keyword hints collected from video descriptions, ASR, or subtitle text.
    NATURAL_KEYWORDS: tuple[str, ...] = (
        "handheld",
        "现场拍摄",
        "实拍",
        "vlog",
        "采访",
        "直播",
        "街拍",
        "camera shake",
        "现场收音",
    )  # Natural-shooting hints that offset false positives in heuristic fallback mode.

    def detect(self, item: dict[str, Any], operator: "VideoAIGCDetectOperator") -> tuple[float | None, dict[str, Any]]:
        """Estimate video AIGC risk from existing workflow intermediates.

        Business logic:
            1. Reuse frame descriptions, ASR text, subtitle text, and visual keywords from upstream operators.
            2. Score suspicious AI cues such as generation-related keywords, low frame diversity, and limited subtitle/speech evidence.
            3. Score natural-capture cues to offset false positives.
            4. Return a bounded fallback risk score with traceable evidence.

        Args:
                item (dict[str, Any]): Current sample dictionary.
                operator (VideoAIGCDetectOperator): Owning operator instance.

        Returns:
            tuple[float | None, dict[str, Any]]: Fallback score and evidence payload.

        Examples:
            >>> detector = LocalHeuristicVideoAIGCDetector()
            >>> sample = {"intermediate": {"vlm_frame_descriptions": ["AI generated avatar speaking"]}, "metrics": {}}
            >>> detector.detect(sample, VideoAIGCDetectOperator({}))[0] > 0
            True
        """
        intermediate = item.get("intermediate", {})
        metrics = item.get("metrics", {})
        descriptions = [str(text) for text in as_list(intermediate.get("vlm_frame_descriptions", [])) if str(text).strip()]
        subtitle_text = str(intermediate.get("subtitle_text", "") or "")
        asr_text = str(intermediate.get("asr_text", "") or "")
        visual_keywords = [str(token).lower() for token in as_list(intermediate.get("visual_keywords", [])) if str(token).strip()]
        combined_text = " ".join(descriptions + [subtitle_text, asr_text, " ".join(visual_keywords)]).lower()

        ai_keyword_hits = sorted({keyword for keyword in self.AI_KEYWORDS if keyword in combined_text})
        natural_keyword_hits = sorted({keyword for keyword in self.NATURAL_KEYWORDS if keyword in combined_text})
        risk_score = 0.0

        if ai_keyword_hits:  # Explicit generation cues provide the strongest fallback signal.
            risk_score += 0.55
        if bool(metrics.get("freeze_frame_ratio")) and float(metrics["freeze_frame_ratio"]) >= float(
            operator.config.get("freeze_frame_risk_threshold", 0.9)
        ):
            risk_score += 0.15
        if bool(metrics.get("video_qr_detected")):  # QR overlays are common in short generated promo videos.
            risk_score += 0.1
        keyframe_count = int(metrics.get("keyframe_count") or 0)
        visual_description_count = len(descriptions)
        if keyframe_count >= 2 and visual_description_count and len(set(descriptions)) <= 1:
            risk_score += 0.1
        if visual_keywords and len(set(visual_keywords)) <= int(operator.config.get("max_repeated_visual_keywords", 3)):
            risk_score += 0.05
        if subtitle_text.strip() or asr_text.strip():
            risk_score -= 0.1
        if natural_keyword_hits:
            risk_score -= 0.15

        score = bounded_float(risk_score)
        evidence = {
            "backend": "fallback",
            "ai_keyword_hits": ai_keyword_hits,
            "natural_keyword_hits": natural_keyword_hits,
            "description_count": visual_description_count,
            "keyframe_count": keyframe_count,
            "freeze_frame_ratio": metrics.get("freeze_frame_ratio"),
            "video_qr_detected": bool(metrics.get("video_qr_detected")),
            "subtitle_text_available": bool(subtitle_text.strip()),
            "asr_text_available": bool(asr_text.strip()),
        }
        return score, evidence


class VideoAIGCDetectOperator(VideoOperator):
    operator_name: str = "video_aigc_detect"  # Operator identifier used by workflow configs and the registry.

    def setup(self) -> None:
        """Initialize detector backends for video AIGC checks.

        Business logic:
            1. Read the preferred detector backend from operator config.
            2. Build the fallback heuristic detector.
            3. Keep the detector interface isolated so model backends can be added later without changing workflow contracts.

        Args:
                None: This hook does not take input parameters.

        Returns:
            None: The hook prepares detector state in place.

        Examples:
            >>> operator = VideoAIGCDetectOperator({})
            >>> operator.setup() is None
            True
        """
        self.detector_backend = str(self.config.get("detector_backend", "fallback"))
        self.detectors = {"fallback": LocalHeuristicVideoAIGCDetector()}

    def process(self, item: dict) -> dict:
        """Estimate whether one video sample is likely AI-generated.

        Business logic:
            1. Skip non-video samples or missing videos.
            2. Run the configured detector backend and fall back to local heuristics when needed.
            3. Record AIGC score, backend, evidence, and threshold-based decision.
            4. Append a dedicated issue when the score exceeds the configured threshold.

        Args:
                item (dict): Current sample dictionary.

        Returns:
            dict[str, Any]: Updated sample dictionary.

        Examples:
            >>> operator = VideoAIGCDetectOperator({})
            >>> operator.setup()
            >>> sample = {"modality": "video", "payload": {"video_path": "demo.mp4"}, "issues": [], "metrics": {}, "intermediate": {}}
            >>> operator.process(sample)["metrics"]["video_aigc_backend"]
            'fallback'
        """
        if self.should_skip(item) or has_any_issue(item, {"video_missing", "decode_failed", "no_video_stream"}):  # Skip when the sample cannot be processed as a valid video.
            return item
        score, evidence = self._run_detector(item)
        threshold = float(self.config.get("video_aigc_threshold", 0.55))
        suspected = score is not None and score >= threshold
        self.set_metric(item, "video_aigc_score", None if score is None else round(score, 4))
        self.set_metric(item, "video_aigc_threshold", round(threshold, 4))
        self.set_metric(item, "video_aigc_backend", evidence.get("backend", self.detector_backend))
        self.set_metric(item, "suspected_video_aigc", bool(suspected))
        self.set_metric(item, "video_aigc_evidence", evidence)
        if suspected:  # Keep the video-AIGC decision independent from the generic quality score.
            self.add_issue(item, "suspected_video_aigc")
        return item

    def _run_detector(self, item: dict[str, Any]) -> tuple[float | None, dict[str, Any]]:
        """Run the configured detector backend with fallback protection.

        Business logic:
            1. Select the preferred detector backend from runtime config.
            2. Execute it and validate the returned score.
            3. Fall back to the local heuristic detector when the preferred backend fails or returns no score.

        Args:
                item (dict[str, Any]): Current sample dictionary.

        Returns:
            tuple[float | None, dict[str, Any]]: Detector score and evidence payload.

        Examples:
            >>> operator = VideoAIGCDetectOperator({})
            >>> operator.setup()
            >>> operator._run_detector({"intermediate": {}, "metrics": {}})[1]["backend"]
            'fallback'
        """
        detector = self.detectors.get(self.detector_backend) or self.detectors["fallback"]
        try:
            score, evidence = detector.detect(item, self)
        except Exception as exc:
            score = None
            evidence = {"backend": self.detector_backend, "error": str(exc)}
        if score is not None:
            return bounded_float(score), evidence
        fallback_detector = self.detectors["fallback"]
        fallback_score, fallback_evidence = fallback_detector.detect(item, self)
        if evidence.get("error"):  # Preserve primary-backend failure context for debugging and audits.
            fallback_evidence["fallback_from_error"] = evidence["error"]
        return bounded_float(fallback_score), fallback_evidence
